/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StartUp;

import Entities.User;
import GUI.JHome;
import IServices.IUserServices;
import Services.UserServices;
import javax.swing.JOptionPane;

/**
 *
 * @author Zyad
 */
public class jSignUp extends javax.swing.JPanel {

    /**
     * Creates new form jLogin
     */
    public jSignUp(JStartUp jsu) {
        initComponents();
        _UserServices = new UserServices();
        _JStartUp = jsu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSignUp = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        tConfirmPassword = new javax.swing.JPasswordField();

        bSignUp.setText("Sign Up");
        bSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignUpMouseClicked(evt);
            }
        });
        bSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignUpActionPerformed(evt);
            }
        });

        bLogin.setText("Login");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });

        jLabel1.setText("USERNAME");

        jLabel4.setText("PASSWORD");

        jLabel5.setText("CONFIRM PASSWPRD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(tPassword)
                            .addComponent(tUsername)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bLogin)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(bSignUp)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(bLogin)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // -> Log In
    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        _JStartUp.home();
    }//GEN-LAST:event_bLoginMouseClicked
    
    // Sign In -> Home
    private void bSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignUpMouseClicked

        String name=tUsername.getText().toString();
        String pass=tPassword.getText().toString();
        String coPass=tConfirmPassword.getText().toString();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "PLS ENTER USERNAME");
        }
        else if(pass.equals("")){
            JOptionPane.showMessageDialog(null, "PLS ENTER PASSWORD");
        }
        else if(coPass.equals("")){
            JOptionPane.showMessageDialog(null, "PLS ENTER CONFIRM PASSWORD");
        }
        else if(!pass.equals(coPass)){
            JOptionPane.showMessageDialog(null, " password and confirm password doesn't match");
        }
        if(!name.equals("")&&!pass.equals("")&&!coPass.equals("")&&pass.equals(coPass))
        {
        JOptionPane.showMessageDialog(null, "Account created successfully "+name);
        
        User user = new User();
        user.username = name;
        user.password = pass;
        
        _UserServices.signUp(user);
        
        //Add Sign Up
        if(true) {
            _JStartUp.dispose();
            JHome _JHome=new JHome();
            _JHome.setLocationRelativeTo(null);
            _JHome.setResizable(false);
            _JHome.setVisible(true);
        }
        }
    }//GEN-LAST:event_bSignUpMouseClicked

    private void bSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSignUpActionPerformed
    
    
    private JStartUp _JStartUp;
    private IUserServices _UserServices;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField tConfirmPassword;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
