/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.StartUp;

import GUI.JHome;
import IServices.IAccountServices;
import Services.AccountServices;

/**
 *
 * @author Zyad
 */
public class jSignUp extends javax.swing.JPanel {

    /**
     * Creates new form jLogin
     */
    public jSignUp(JStartUp jsu) {
        initComponents();
        
        _AccountService = new AccountServices();
        _JStartUp = jsu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSignUp = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        bSignUp.setText("SignUp");
        bSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignUpMouseClicked(evt);
            }
        });

        bLogin.setText("Login");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });

        jLabel1.setText("SignUp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bLogin)
                        .addComponent(bSignUp)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(bLogin)
                .addGap(18, 18, 18)
                .addComponent(bSignUp)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    // -> Log In
    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        _JStartUp.home();
    }//GEN-LAST:event_bLoginMouseClicked

    // Sign In -> Home
    private void bSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignUpMouseClicked
        boolean result = _AccountService.signUp("", "");
        if(result) {
            _JStartUp.dispose();
            new JHome().setVisible(true);
        }
    }//GEN-LAST:event_bSignUpMouseClicked
    
    
    private JStartUp _JStartUp;
    
    private IAccountServices _AccountService;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignUp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
